  - name: install InfluxDB package (CentOS)
    shell: sudo yum localinstall influxdb_package.rpm
  

  - name: Install required packages for Grafana (CentOS)
    yum:
      name: epel-release
      state: present

  - name: Add Grafana YUM repository (CentOS)
    yum_repository:
      name: grafana
      description: Grafana repository
      baseurl: https://packages.grafana.com/oss/rpm
      gpgcheck: yes
      gpgkey: https://packages.grafana.com/gpg.key
      enabled: yes
    when: not (ansible_facts['yum_repos']|default([]) | select('match', 'grafana') | list)

  - name: Install Grafana (CentOS)
    package:
      name: grafana
      state: present

  - name: Update Grafana configuration to allow network host
    lineinfile:
      dest: /etc/grafana/grafana.ini
      regexp: '^;http_addr ='
      line: 'http_addr = 0.0.0.0'

  - name: Update Grafana configuration to change the default port to 3000
    lineinfile:
      dest: /etc/grafana/grafana.ini
      regexp: '^;http_port ='
      line: 'http_port = 3000'

  - name: prothemetus download directory (CentOS)
    file:
      path: ~/prometheus
      state: directory

  - name: Downloading and extracting Prometheus (CentOS)
    unarchive:
      src: https://github.com/prometheus/prometheus/releases/download/v2.8.1/prometheus-2.8.1.linux-amd64.tar.gz
      dest: ~/prometheus
      remote_src: yes
      mode: 0777
      owner: root
      group: root


  - name: Stop the Prometheus service (CentOS)
    service:
      name: prometheus
      state: stopped
    async: 300
    poll: 0
    ignore_errors: yes

  - name: Adding the Prometheus executables to a PATH
    tags: executables
    shell: |
      cd ~/prometheus/prometheus*
      cp -r . /usr/local/bin/prometheus

  - name: Copying the Prometheus Configuration (CentOS)
    copy:
      src: prometheus.service
      dest: /etc/systemd/system/prometheus.service
      owner: root
      group: root
      mode: 777


  - name: Start and enable Grafana service (CentOS)
    service:
      name: grafana-server
      state: started
      enabled: yes

  - name: enable / start Prometheus (CentOS)
    service:
      name: prometheus
      state: started
      enabled: yes
